language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
install:
- dotnet restore
script:
- dotnet build
- dotnet test VideoAppBLLTests/VideoAppBLLTests.csproj
branches:
  only:
  - master
  - development
notifications:
  email: false
  slack: cs2016a:MrE8tgSmsfcVCMVTa1JgT78G
  on_success: change
  on_failure: change